nucleotides = ['A', 'C', 'G', 'T']

# Mathcing Nucleotids in DNA for reversed transcription 
dna_reverse_complement = {'A':'T', 
                          'T': 'A', 
                          'G': 'C', 
                          'C' : 'G'}

def reverse_complement(seq: str) -> str:
    """ Takes the string DNA and return the reversed dna string 
     by replacing the A to T and C to G and reversing the string after all """
    return ''.join([dna_reverse_complement[nuc] for nuc in seq])[::-1]

dna1 = 'TACAATGTGACTCTCAATACTATAATCTGCTTAAATAACGAGGCAGAGAAATATGCAGGAAACGAATAGTCATGCGGTGCATAACTCAGGTCAGAATCGTTATGCGCGACACGTTCCCTCTCTGTTCAGGTACAGATGGTTTGAGTTGTGGCTCCGCCGTCGTTAGTAGAAAGGAACATTCGCTCGCACAAGCAATGACATTTAGTGAATAAAATCGTAGATCGCTGCCCTCAAATCTATGTCTTGTAGAGAAGATGCGATGGTCCCTGTAGTGTTATGGCGTTCAAACGGCCGTAAGCTATGTGGTCACAAGGTGAGAGATACCTGCAGTCTGCTTACGCAGCAGTTCTTGCTCTCTACAGCGCTAACTAAGCCCATGGTGGCGGAGTCAGACGCACCCCCATTGACTATAGACTTGACATCGCTAAGGGAAGGGGTACAGTCCCCGCATGATAGTTCACTCCCGGCTGGTGTACAGACCTCAGCATAGGCGTGTGATGTTCTCTAATGGCGAAAATGATTACAGTTCCATCCAGTCCTCCGAACCGAGTGGAGGGACGTCGGCAGGGTGTGAGCGAAATCATAAACTATGGAGGCATGATTTCTTCAAGCCTTCGGTTCAAACTCGGGTATGCGGTGGCCTGACTCTTTCAAAACACATACGACGCTAGAGTAGCCGAAAATCCAGGAGTCGCGGTCGTTCGTGGCGCACGCCTATCGCATACACGATGTGTTGGTCAAAGACCATGCAAATGATTAACCGATTCGCTGGTCTCTTTAGGTCCGGGTGGTTCGAATAGATCAGACTGTTCGTACGCCGGGCATACGGAGTTACGGAGTTTGTTGGGAACTTGGATTAAATGCTTGGTCTTATCAGGGCACGATATCTGGGGTTC'
print(reverse_complement(dna1))
